-- Migration neutralizada.
-- A versão original recalculava status de crm_cobrancas usando keys antigas
-- (em_cobranca, pendente, atrasado, 5_dias_de_atraso, 45_dias_..., etc.) que
-- não existem mais em crm_cobranca_statuses. Isso causava cards em colunas
-- inexistentes após cada execução do deploy.sh.
--
-- O fluxo de status correto é gerenciado por:
--   • supabase/functions/ssotica-sync (entrada por dias de atraso)
--   • supabase/functions/cobranca-flow-advance (avanço pelo fluxo configurado)
--
-- Mantida vazia para preservar o histórico de migrations.
SELECT 1;
